version: '3'

services:

  ui-client:
    build: 
      dockerfile: Dockerfile
      context: ./ui-client
    ports:
      - 80:80

  ws-server:
    build: 
      dockerfile: Dockerfile
      context: ./ws-server